// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaURHS9qpE00Bp6V9xfYIKDAjAC7AarQI',
    appId: '1:603591911717:web:b789f75276edfaad9352cc',
    messagingSenderId: '603591911717',
    projectId: 'social-media-app-550ec',
    authDomain: 'social-media-app-550ec.firebaseapp.com',
    storageBucket: 'social-media-app-550ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIzci_Y0lw63DwuOsar209OkPyl-tqBY',
    appId: '1:603591911717:android:28245727d39c6f189352cc',
    messagingSenderId: '603591911717',
    projectId: 'social-media-app-550ec',
    storageBucket: 'social-media-app-550ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG_gxyOLO-tqNXpIfr8FNIiqENgkcyyDo',
    appId: '1:603591911717:ios:b570c102bd3ec4779352cc',
    messagingSenderId: '603591911717',
    projectId: 'social-media-app-550ec',
    storageBucket: 'social-media-app-550ec.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG_gxyOLO-tqNXpIfr8FNIiqENgkcyyDo',
    appId: '1:603591911717:ios:b570c102bd3ec4779352cc',
    messagingSenderId: '603591911717',
    projectId: 'social-media-app-550ec',
    storageBucket: 'social-media-app-550ec.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaURHS9qpE00Bp6V9xfYIKDAjAC7AarQI',
    appId: '1:603591911717:web:383b3f7abd77829b9352cc',
    messagingSenderId: '603591911717',
    projectId: 'social-media-app-550ec',
    authDomain: 'social-media-app-550ec.firebaseapp.com',
    storageBucket: 'social-media-app-550ec.appspot.com',
  );
}
