// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPd6WhM4eFNIYHo_2PzoABjx-cz2o2uWk',
    appId: '1:950599793902:web:0375019ba6e75057d187ff',
    messagingSenderId: '950599793902',
    projectId: 'bytewise-task01-auth',
    authDomain: 'bytewise-task01-auth.firebaseapp.com',
    storageBucket: 'bytewise-task01-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgAGb7a9zXzTmLmhw70pmc1Gq9BdZS_QI',
    appId: '1:950599793902:android:af312ec2c5e185d6d187ff',
    messagingSenderId: '950599793902',
    projectId: 'bytewise-task01-auth',
    storageBucket: 'bytewise-task01-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuc53wOBkAy85JOFOLTTH8OCWyj4DPJP0',
    appId: '1:950599793902:ios:aef089a3892daa0ad187ff',
    messagingSenderId: '950599793902',
    projectId: 'bytewise-task01-auth',
    storageBucket: 'bytewise-task01-auth.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );
}
